apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-db
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: debtmanager
            - name: POSTGRES_USER
              value: leandro
            - name: POSTGRES_PASSWORD
              value: senha
